<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="/Users/orangexception/exercism/csharp/gigasecond/output/Gigasecond.dll" total="3" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2014-11-12" time="09:29:01">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.1433" os-version="Unix 13.4.0.0" platform="Unix" cwd="/Users/orangexception/exercism/csharp/gigasecond" machine-name="BRADLEYs-MacBook-Pro.local" user="orangexception" user-domain="BRADLEYs-MacBook-Pro.local" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="/Users/orangexception/exercism/csharp/gigasecond/output/Gigasecond.dll" executed="True" result="Success" success="True" time="0.027" asserts="0">
    <results>
      <test-suite type="TestFixture" name="GigasecondTest" executed="True" result="Success" success="True" time="0.022" asserts="0">
        <results>
          <test-case name="GigasecondTest.Another_date" executed="True" result="Success" success="True" time="0.011" asserts="1" />
          <test-case name="GigasecondTest.First_date" executed="True" result="Success" success="True" time="0.000" asserts="1" />
          <test-case name="GigasecondTest.Yet_another_date" executed="True" result="Success" success="True" time="0.000" asserts="1" />
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>